### ISSUE TITLE
README installation instructions point to wrong library

### ISSUE THREAD

**Issue by abrthel** [owlsdepartment/vue-tree-routes#5]
Install instructions in readme point to 
- @owlsdepartment/vuex-typed

where npm package gallery points to package
- @owlsdepartment/vue-tree-routes

**Comment by F0rsaken** [comment]
@abrthel thx for noticing and sorry for late response (I didn't got any notification) and I will fix it ASAP!

Btw, let me know if you're using this library

**Comment by abrthel** [comment]
It's all good.

I was using the library but unfortunately I had to write a custom one to handle our particular use-case. Solid work though, it was a treat while we used it.

**Comment by F0rsaken** [comment]
@abrthel nice to hear it! I'm kind of curious what was your use-case that lead to this 🤔

**Comment by abrthel** [comment]
I'm working on an online course that has locked stages and each stage can have multiple routes underneath it but they don't act like children in the standard vue sense. We also needed to track locked/unlocked states on particular nodes based on if the previous state is marked as "completed". It's kind of an odd setup but its a client requirement so ultimately it was just easier for us to control all of the levers.
